test: add entry controller tests (#212)
* test: initial entry controller unit tests
- Set up test suite.
  - Mock `EntryServices`, `Request`, `Response`, and `NextFunction`.
- Create test suite for `EntryController`.
  - Add tests for `getAllEntries`.

* test: add createEntry tests
- Add `createEntry` tests.
- Update mocks.
  - Simplify `mockReq`.
  - Make `mockNext` a `jest.Mock`.
- Remove mocked services that there are no tests for.
- Update `getEntry` wrt the updated `mockReq`.

* test: add additional getAllEntries test

* refactor: rename getAllEntriesInJournal to getAllEntries

* test: add getAnEntry tests

* test: add updateEntry, deleteEntry, and getEntryAnalysis tests
- Add unit tests for `updateEntry`.
- Add unit tests for `deleteEntry`.
- Add unit tests for `getEntryAnalysis`.
  - Resolve error: `entryAnalysis.toObject` is not a function.
    - Remove unnecessary `toObject` cast.

* test: add updateEntryAnalysis tests
- Add `updateEntryAnalysis` tests.
- Remove unnecessary `toObject` cast on `entryAnalysis` returned from `updateEntryAnalysis` service.

* test: add getEntryConversation, createEntryConversation, and updateEntryConversation tests

- Add `getEntryConversation` tests.
  - Remove unnecessary `toObject` cast.
- Add `createEntryConversation` tests.
  - Remove unused logic to check for empty response.
    - An error will be thrown by `getAnalysisCompletion` in entryConversation.ts before this logic is reached.
- Add `updateEntryConversation` tests.
  - Remove unnecessary `toObject` cast.
  - Note that flash messages are not sent on successful update (see FIXME).

* test: ensure an error is returned if journal.config is not found
- Add test to `createEntry` test sub-suite.

* fix: remove duplicate mock